// --- Arquivo: src/main/preload.js ---

const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('electronAPI', {
  getFirebaseConfig: () => ({
    apiKey: process.env.FIREBASE_API_KEY,
    authDomain: process.env.FIREBASE_AUTH_DOMAIN,
    projectId: process.env.FIREBASE_PROJECT_ID,
    storageBucket: process.env.FIREBASE_STORAGE_BUCKET,
    messagingSenderId: process.env.FIREBASE_MESSAGING_SENDER_ID,
    appId: process.env.FIREBASE_APP_ID,
  }),
  getGeminiApiKey: () => process.env.GEMINI_API_KEY,
  getWhatsappQr: () => ipcRenderer.invoke('get-whatsapp-qr'),
  getWhatsappStatus: () => ipcRenderer.invoke('get-whatsapp-status'),
  onWhatsappQr: (callback) => ipcRenderer.on('whatsapp-qr', (event, qr) => callback(qr)),
  onWhatsappStatus: (callback) => ipcRenderer.on('whatsapp-status', (event, status) => callback(status)),
  whatsappLogout: () => ipcRenderer.invoke('whatsapp-logout'),
  whatsappInitialize: () => ipcRenderer.invoke('whatsapp-initialize'),
  sendWhatsappMessage: (number, message) => ipcRenderer.invoke('send-whatsapp-message', number, message),
  standardizePhoneNumber: (phoneNumber, countryCode) => ipcRenderer.invoke('standardize-phone-number', phoneNumber, countryCode),
  createClientIfNotExists: (data) => ipcRenderer.invoke('create-client-if-not-exists', data),
  updateClient: (clientId, updateData) => ipcRenderer.invoke('update-client', clientId, updateData),
  deleteClient: (id) => ipcRenderer.invoke('delete-client', id),
  getClientAppointments: (clientId) => ipcRenderer.invoke('get-client-appointments', clientId),
  updateAppointmentNote: (data) => ipcRenderer.invoke('update-appointment-note', data),
  deleteOrder: (id) => ipcRenderer.invoke('delete-order', id),
  updateOrderStatus: (data) => ipcRenderer.invoke('update-order-status', data),
  updateOrder: (id, data) => ipcRenderer.invoke('update-order', { id, data }),
  generateTextWithAI: (data) => ipcRenderer.invoke('generate-ai-response', data),
  updateAiSettings: (settings) => ipcRenderer.invoke('update-ai-settings', settings),
  uploadMenuFile: (fileData) => ipcRenderer.invoke('upload-menu-file', fileData),
  getProducts: () => ipcRenderer.invoke('get-products'),
  addProduct: (p) => ipcRenderer.invoke('add-product', p),
  deleteProduct: (id) => ipcRenderer.invoke('delete-product', id),
  toggleProductStatus: (data) => ipcRenderer.invoke('toggle-product-status', data),
  updateProductStock: (data) => ipcRenderer.invoke('update-product-stock', data),
  createManualOrder: (order) => ipcRenderer.invoke('create-manual-order', order),
  getPrinters: () => ipcRenderer.invoke('get-printers'),
  printOrder: (order) => ipcRenderer.invoke('print-order-manual', order),
  selectProductImage: (id) => ipcRenderer.invoke('select-product-image', id),
  sendProductImage: (data) => ipcRenderer.invoke('send-product-image', data),
  getScheduledOrders: () => ipcRenderer.invoke('get-scheduled-orders'),
  printReport: (data) => ipcRenderer.invoke('print-report', data),
  uploadConfigImage: (data) => ipcRenderer.invoke('upload-config-image', data),
  sendDailyShowcase: (chatId) => ipcRenderer.invoke('send-daily-showcase', chatId),
  createScheduledOrder: (data) => ipcRenderer.invoke('create-scheduled-order', data),
  updateScheduledOrder: (data) => ipcRenderer.invoke('update-scheduled-order', data),
  deleteScheduledOrder: (id) => ipcRenderer.invoke('delete-scheduled-order', id),
  printCloseRegister: (data) => ipcRenderer.invoke('print-close-register', data),
  startMassSend: (message, recipients) => ipcRenderer.invoke('start-mass-send', message, recipients),
  stopMassSend: () => ipcRenderer.invoke('stop-mass-send'),
  onMassSendStatus: (callback) => ipcRenderer.on('mass-send-status', (event, status) => callback(status)),
});